- name: restart az-devops-agent
  become: true
  systemd:
    daemon_reload: true
    state: restarted
    name: azure_devops_agent

- name: start az-devops-agent
  become: true
  systemd:
    daemon_reload: true
    state: started
    name: azure_devops_agent

- name: stop az-devops-agent
  become: true
  systemd:
    daemon_reload: true
    state: stopped
    name: azure_devops_agent
